# runtime: python27
# api_version: 1
# threadsafe: true

# handlers:
# - url: /.*
#   script: shootinstraight3d.app

# libraries:
# - name: webapp2
#   version: latest

application: shootinstraight3d
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /static
  static_dir: static

- url: /.*
  script: shootinstraight3d.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: "1.1.7"
